### ISSUE TITLE
Jekyll or plain html?

### ISSUE THREAD

**Issue by octoshrimpy** [RetroCraft/master-tracker#1]
Jekyll would give us to use scss/sass (which is easier than raw css), although raw html is easier for those starting out.  I can write a very basic jekyll+scss tutorial if need be.

**Comment by raehart** [comment]
Its mostly just markdown, I don't think we need Jekyll for that.  What type of things do we want/ need to do with css?

**Comment by octoshrimpy** [comment]
@Brigette-Eckert it wa sswitched to MD recently. this issue is from the beginning of the repo and was never closed.
